# Config file for DeepForest-pytorch module

train:
    #Cpu workers for data loaders
    workers: 10
    
    #Optomizer  initial learning rate
    lr: 0.001
    
    #Print loss every n epochs
    print_freq: 1
    
    epochs: 10
    
    batch_size: 3
